### ISSUE TITLE
点击 热门 不能跳转到热门那部分

### ISSUE THREAD

**Issue by Skqing** [chsmy/CitySelector#1]

**Comment by chsmy** [comment]
这个在点击事件里面加一个判断就可以了。如果是热门就跳到listview的0的位置。代码已提交可以看下

**Comment by chsmy** [comment]
这个在点击事件里面加一个判断就可以了。如果是热门就跳到listview的0的位置。代码已提交可以看下

**Comment by chsmy** [comment]
这个在点击事件里面加一个判断就可以了。如果是热门就跳到listview的0的位置。代码已提交可以看下
